version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/app/storage
      - ./backend:/app
    environment:
      - GIN_MODE=debug
    depends_on:
      - ffmpeg

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080

  ffmpeg:
    image: jrottenberg/ffmpeg:4.4-alpine
    volumes:
      - ./storage:/storage
    command: tail -f /dev/null